[project]
name = "mediawiki-pages-dump"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ipython>=9.5.0",
    "mysql-connector-python>=8.0.0",
]
